app_key: "3e5rr36wyuxma79"
app_secret: <%= ENV["DROPBOX_APP_SECRET"] %>
access_token: "fnyeo33s1a3a74cq"
access_token_secret: <%= ENV["DROPBOX_ACCESS_TOKEN_SECRET"] %>
user_id: "324226280"
access_type: "app_folder"
